name: IcpKit Tests

on:
  push:
  pull_request:
    branches:
      main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -quiet -scheme IcpKit-Package -sdk iphonesimulator17.5 -destination "OS=17.5,name=iPhone 15 Pro" '-skip-testing:IcpKitTests/ICPCryptographyTests/testBlsSignatureVerification'
      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v4.5.0
